In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)  # Show all columns when displaying DataFrames

In [3]:
org_df = pd.read_csv('20251012_bulk_export/organizations.csv')
org_des_df = pd.read_csv('20251012_bulk_export/organization_descriptions.csv')

In [9]:
org_df = org_df[org_df['country_code'].isin(['USA', 'CAN'])]  # filter to US and Canada only
org_df = org_df[org_df['roles'] != 'investor']  # filter to keep only organizations that are not investors

In [10]:
org_df.head()

,uuid,name,type,permalink,cb_url,rank,created_at,updated_at,legal_name,roles,domain,homepage_url,country_code,state_code,region,city,address,postal_code,status,short_description,category_list,category_groups_list,num_funding_rounds,total_funding_usd,total_funding,total_funding_currency_code,founded_on,last_funding_on,closed_on,employee_count,email,phone,facebook_url,linkedin_url,twitter_url,logo_url,alias1,alias2,alias3,primary_role,num_exits
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,organization,wetpaint,https://www.crunchbase.com/organization/wetpaint,258083.0,2007-05-25 13:51:27,2024-07-09 01:22:43,"wetpaint.com, inc.",company,wetpaint.com,http://www.wetpaint.com/,USA,NY,New York,New York,902 Broadway 11th Floor New,10010,acquired,Wetpaint offers an online social publishing pl...,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",3.0,3.975000e+07,3.975000e+07,USD,2005-06-01,2008-05-19,NaN,51-100,info@wetpaint.com,206-859-6300,https://www.facebook.com/Wetpaint,https://www.linkedin.com/company/recruitment-c...,https://twitter.com/wetpainttv,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN
2,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,organization,digg,https://www.crunchbase.com/organization/digg,23412.0,2007-05-26 03:03:23,2025-06-17 04:56:34,"Digg Holdings, LLC",company,digg.com,http://www.digg.com,USA,NY,New York,New York,NaN,NaN,acquired,Digg operates a website that enables its users...,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",7.0,4.900000e+07,4.900000e+07,USD,2004-10-11,2024-11-18,NaN,11-50,feedback@digg.com,NaN,http://www.facebook.com/digg,http://www.linkedin.com/company/digg,https://x.com/digg,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN
4,df662812-7f97-0b43-9d3e-12f64f504fbb,Meta,organization,facebook,https://www.crunchbase.com/organization/facebook,1276.0,2007-05-26 04:22:15,2024-10-01 00:57:57,"Meta Platforms, Inc.","company,investor",meta.com,https://www.meta.com,USA,CA,California,Menlo Park,1 Hacker Way,94025,operating,Meta is a social technology company that enabl...,"Artificial Intelligence (AI),Augmented Reality...","Artificial Intelligence (AI),Data and Analytic...",18.0,5.460882e+10,5.460882e+10,USD,2004-02-04,2025-08-08,NaN,10000+,press@meta.com,NaN,https://www.facebook.com/Meta,https://www.linkedin.com/company/meta,https://x.com/Meta,https://images.crunchbase.com/image/upload/t_c...,Facebook,FB,Meta Platforms,company,1.0
8,60485007-8856-bbac-aa1b-c535c41f5f47,Omnidrive,organization,omnidrive,https://www.crunchbase.com/organization/omnidrive,628730.0,2007-05-27 10:25:32,2019-10-03 06:30:53,NaN,company,omnidrive.com,http://www.omnidrive.com,USA,CA,California,Palo Alto,Suite 200 654 High Street,94301,closed,Omnidrive provides online storage facilities t...,"E-Commerce,File Sharing,Internet,Social Media,...","Commerce and Shopping,Internet Services,Media ...",1.0,8.000000e+05,8.000000e+05,USD,2005-11-01,2006-12-01,2008-09-15,unknown,info@omnidrive.com,NaN,http://www.facebook.com/Nomadesk,NaN,http://twitter.com/Nomadesk,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN
9,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni,organization,geni,https://www.crunchbase.com/organization/geni,270094.0,2007-06-01 02:52:34,2024-07-23 01:56:23,"Geni, Inc.",company,geni.com,http://www.geni.com,USA,CA,California,West Hollywood,9229 W. Sunset Blvd.,90069,acquired,Geni is an online community of genealogists co...,"Collaboration,Communities","Community and Lifestyle,Other",3.0,1.500000e+07,1.500000e+07,USD,2006-06-01,2009-01-19,NaN,11-50,NaN,NaN,https://www.facebook.com/genidotcom/,https://www.linkedin.com/company/geni-com/about/,http://twitter.com/geni,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN

In [11]:
org_des_df.head()

,uuid,name,type,permalink,cb_url,rank,created_at,updated_at,description
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,organization,wetpaint,https://www.crunchbase.com/organization/wetpaint,258083.0,2007-05-25 13:51:27,2024-07-09 01:22:43,Wetpaint is a technology platform company that...
1,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,organization,zoho,https://www.crunchbase.com/organization/zoho,75697.0,2007-05-26 02:30:28,2025-07-16 05:28:35,"Zoho offers a suite of business, collaboration..."
2,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,organization,digg,https://www.crunchbase.com/organization/digg,23412.0,2007-05-26 03:03:23,2025-06-17 04:56:34,Digg Inc. operates a website that enables its ...
3,f4d5ab44-058b-298b-ea81-380e6e9a8eec,Omidyar Network,organization,omidyar-network,https://www.crunchbase.com/organization/omidya...,212736.0,2007-05-26 03:21:34,2024-06-06 16:26:51,"Pierre Omidyar, the founder of eBay, and his w..."
4,df662812-7f97-0b43-9d3e-12f64f504fbb,Meta,organization,facebook,https://www.crunchbase.com/organization/facebook,1276.0,2007-05-26 04:22:15,2024-10-01 00:57:57,Meta is a social technology company that enabl...

In [18]:
org_clean_df = org_df[['uuid','name','category_list','category_groups_list','short_description']]
org_clean_df = pd.merge(org_des_df[['uuid','description']], org_clean_df, on='uuid',how='right')

In [20]:
org_clean_df.head()

,uuid,description,name,category_list,category_groups_list,short_description
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint is a technology platform company that...,Wetpaint,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",Wetpaint offers an online social publishing pl...
1,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg Inc. operates a website that enables its ...,Digg,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",Digg operates a website that enables its users...
2,df662812-7f97-0b43-9d3e-12f64f504fbb,Meta is a social technology company that enabl...,Meta,"Artificial Intelligence (AI),Augmented Reality...","Artificial Intelligence (AI),Data and Analytic...",Meta is a social technology company that enabl...
3,60485007-8856-bbac-aa1b-c535c41f5f47,"Currently in public beta, Omnidrive makes it e...",Omnidrive,"E-Commerce,File Sharing,Internet,Social Media,...","Commerce and Shopping,Internet Services,Media ...",Omnidrive provides online storage facilities t...
4,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni is an online community of casual and expe...,Geni,"Collaboration,Communities","Community and Lifestyle,Other",Geni is an online community of genealogists co...

In [ ]:
cats = org_clean_df['category_list']
cats_exploded = cats.str.split(',').explode().str.strip()
all_categories = cats_exploded.dropna().unique()

In [25]:
len(all_categories)

800

In [24]:
all_categories

array(['Publishing', 'Social Media', 'Social Media Management',
       'Internet', 'Social Network', 'Artificial Intelligence (AI)',
       'Augmented Reality', 'Metaverse', 'Virtual Reality', 'E-Commerce',
       'File Sharing', 'Software', 'Web Hosting', 'Collaboration',
       'Communities', 'Mobile', 'News', 'Photography', 'Video',
       'Advertising', 'Digital Media', 'Information Services',
       'Blogging Platforms', 'Web3', 'Content', 'Personalization',
       '3D Technology', 'Developer Tools', 'Audiobooks', 'Books',
       'EBooks', 'Podcast', 'Music', 'Music Streaming',
       'Telecommunications', 'Auctions', 'Marketplace', 'Retail',
       'Big Data', 'Online Portals', 'Sports', 'Location Based Services',
       'Real Time', 'Cyber Security', 'Security', 'TV', 'Broadcasting',
       'Media and Entertainment', 'Contact Management',
       'Digital Entertainment', 'Communications Infrastructure',
       'Enterprise Software', 'Hardware', 'Natural Language Processing',
       'Search Engine', 'Advertising Platforms', 'Marketing',
       'Public Relations', 'Ad Exchange', 'B2B', 'Knowledge Management',
       'Gaming', 'Sales', 'Virtual Currency', 'Content Delivery Network',
       'Film', 'Banking', 'Finance', 'Financial Services',
       'Venture Capital', 'Social News', 'Brand Marketing',
       'TV Production', 'Video Streaming', 'FinTech', 'Machine Learning',
       'Personal Finance', 'SaaS', 'Social', 'Consumer',
       'Service Industry', 'Crowdfunding', 'Lending', 'Mortgage',
       'Content Creators', 'Social Media Marketing', 'Messaging', 'Apps',
       'VoIP', 'Food and Beverage', 'Food Processing', 'GPS',
       'Social Bookmarking', 'Predictive Analytics', 'Risk Management',
       'Video Games', 'Audio', 'Browser Extensions', 'Mobile Devices',
       'Database', 'Shopping', 'Dating', 'Lifestyle', 'Celebrity',
       'Email', 'Email Marketing', 'Market Research', 'Internet Radio',
       'Asset Management', 'Funding Platform', 'Insurance', 'Travel',
       'PaaS', 'Web Development', 'Facebook', 'Tourism', 'Transportation',
       'Ticketing', 'Web Design', 'Environmental Engineering',
       'Life Science', 'Software Engineering', 'Analytics',
       'Business Intelligence', 'Android', 'Manufacturing',
       'Infrastructure', 'Photo Sharing', 'Events', 'Mobile Apps',
       'PC Games', 'Virtual World', 'Private Social Networking',
       'Coupons', 'Local', 'Pet', 'Biotechnology', 'Health Care',
       'Pharmaceutical', 'Online Auctions', 'Cloud Computing',
       'Document Management', 'Legal', 'Financial Exchanges',
       'Professional Services', 'Stock Exchanges', 'Content Discovery',
       'Ediscovery', 'Association', 'Event Management',
       'Professional Networking', 'Recruiting', 'Social Recruiting',
       'Data Integration', 'Network Security', 'Physical Security',
       'Wireless', 'Real Estate', 'Content Marketing',
       'Information Technology', 'Medical', 'Flash Storage', 'Concerts',
       'Web Browsers', 'Charity', 'Life Insurance', 'Wealth Management',
       'Consulting', 'Property Management', 'PropTech',
       'Real Estate Brokerage', 'Internet of Things', 'Smart Home',
       'Computer Vision', 'Drones', 'National Security', 'Freelance',
       'Peer to Peer', 'Employment', 'Human Resources', 'Automotive',
       'Classifieds', 'Online Games', 'Consumer Reviews', 'Cooking',
       'Recipes', 'Leisure', 'Teenagers', 'WebOS', 'Ad Network',
       'UX Design', 'Computer', 'CRM', 'iOS', 'Consumer Software',
       'Printing', 'Navigation', 'Shipping', 'E-Learning', 'Education',
       'Universities', 'Virtualization', 'Identity Management',
       'App Marketing', 'Crowdsourcing', 'Consumer Electronics',
       'Electronics', 'Semantic Web', 'Accounting', 'Generative AI',
       'Credit Cards', 'Payments', 'Mobile Payments',
       'E-Commerce Platforms', 'Transaction Processing',
       'Film Distribution', 'Children', 'Amusement Park and Arcade',
       'Animation', 'Consumer Goods', 'Resorts', 'Video on Demand',
       'Film Production', 'Hotel', 'IT Infrastructure', 'Gift', 'Toys',
       'Blockchain', 'Video Chat', 'GreenTech', 'Outdoors', 'Recreation',
       'Recycling', 'MMO Games', 'Snack Food', 'Wholesale',
       'Cloud Data Services', 'Cloud Management', 'Private Cloud',
       'Small and Medium Businesses', 'Alumni', 'Career Planning',
       'Ad Targeting', 'Digital Marketing', 'Open Source', 'Reputation',
       'Graphic Design', 'Image Recognition', 'Photo Editing',
       'Business Development', 'Customer Service', 'Social CRM', 'CMS',
       'Freight Service', 'Warehousing', 'Packaging Services', 'SEO',
       'Creative Agency', 'IaaS', 'Direct Marketing', 'Meeting Software',
       'Independent Music', 'Casual Games', 'Mobile Advertising', 'Art',
       'Fashion', 'Privacy', 'Product Search', 'Journalism', 'Gift Card',
       'Developer APIs', 'Gambling', 'Training', 'Bitcoin', 'Web Apps',
       'Test and Measurement', 'Local Advertising', 'Rental',
       'Government', 'Public Safety', 'Aerospace', 'Shoes', 'Freemium',
       'Micro Lending', 'Non Profit', 'Social Entrepreneurship',
       'Consumer Lending', 'Credit', 'Content Syndication', 'Contests',
       'Lead Generation', 'Sales Automation', 'Local Business', 'SEM',
       "Women's", 'Hospitality', 'Reservations', 'Restaurants',
       'Marketing Automation', 'Digital Signage', 'Logistics',
       'Product Design', 'Fantasy Sports', 'Developer Platform',
       'Speech Recognition', 'Psychology', 'Task Management',
       'Child Care', 'Elder Care', 'Housekeeping Service', 'Tutoring',
       'Advice', 'Parenting', 'Console Games', 'Home Decor',
       'Data Management', 'Google', 'Management Information Systems',
       'mHealth', 'Scheduling', 'Data Visualization',
       'Communication Hardware', 'Casino', 'InsurTech',
       'Wine And Spirits', 'Social Media Advertising', 'ISP',
       'Affiliate Marketing', 'Humanitarian', 'Presentations', 'Solar',
       'Fitness', 'Personal Health', 'Wearables', 'Architecture', 'DIY',
       'Enterprise', 'Geospatial', '3D Printing',
       'Heating  Ventilation  and Air Conditioning (HVAC)',
       'Mechanical Engineering', 'Hospital',
       'Application Performance Management', 'Social Shopping', 'Elderly',
       'EdTech', 'Higher Education', 'Social Impact', 'Clean Energy',
       'Energy Efficiency', 'Sustainability', 'Travel Agency',
       'Semantic Search', 'Copywriting', 'Cloud Infrastructure',
       'Cloud Security', 'Cloud Storage', 'Data Storage', 'SMS',
       'Satellite Communication', 'Intellectual Property', 'Power Grid',
       'Politics', 'Homeland Security', 'Genetics', 'Family',
       'Subscription Service', 'Agriculture', 'AgTech', 'Farming',
       'Mapping Services', 'Legal Tech', 'Q&A', 'Commercial Real Estate',
       'Property Development', 'Lighting', 'Home Health Care',
       'Home Services', 'Network Hardware', 'Fraud Detection',
       'Native Advertising', 'Personal Branding', 'Furniture',
       'Real Estate Investment', 'Spam Filtering',
       'Business Information Systems',
       'Business Process Automation (BPA)', 'Residential',
       'Home Renovation', 'Foreign Exchange Trading', 'Trading Platform',
       'Construction', 'GovTech', 'Project Management', 'DRM',
       'Interior Design', 'Beauty', 'Cosmetics', 'Unified Communications',
       'Video Conferencing', 'Debit Cards', 'Young Adults',
       'Video Editing', 'Corporate Training', 'Wellness',
       'Intelligent Systems', 'Music Venues', 'Musical Instruments',
       'Chemical', 'Industrial', 'Semiconductor', 'Brewing',
       'Price Comparison', 'Data Center', 'Supply Chain Management',
       'App Discovery', 'Food Delivery', 'Video Advertising', 'Religion',
       'Commercial', 'Online Forums', 'Reading Apps', 'Apparel',
       'Collaborative Consumption', 'Delivery Service', 'Event Promotion',
       'Business Travel', 'Operating Systems', 'Energy',
       'Energy Management', 'Robotics', 'Renewable Energy',
       'Energy Storage', 'CleanTech', 'Nanotechnology', 'Gamification',
       'Electric Vehicle', 'Guides', 'Vacation Rental',
       'Industrial Manufacturing', 'Battery', 'Jewelry',
       'Lead Management', 'Product Management', 'Equestrian',
       'Travel Accommodations', 'Language Learning',
       'Innovation Management', 'Dietary Supplements', 'DevOps',
       'Billing', 'Retail Technology', 'Addiction Treatment',
       'E-Signature', 'Angel Investment', 'Delivery', 'Law Enforcement',
       'Water Transportation', 'Cleaning Products', 'Nutrition',
       'Hedge Funds', 'Sales Enablement', 'Point of Sale',
       'Data Collection and Labeling', 'Waste Management', 'Collectibles',
       'Wind Energy', 'Visual Search', 'Employee Benefits',
       'Rental Property', 'Advanced Materials', 'Funerals', 'Data Mining',
       'Incubators', 'Baby', 'Staffing Agency', 'A/B Testing',
       'Biometrics', 'Health Diagnostics', 'Fleet Management',
       'Domain Registrar', 'Electrical Distribution', 'Compliance',
       'Outsourcing', 'Theatre', 'Vertical Search', 'Data Governance',
       'Virtual Goods', 'IT Management', 'Loyalty Programs',
       'Credit Bureau', 'Virtual Assistant',
       'Electronic Health Record (EHR)', 'Text Analytics',
       'Plastics and Rubber Manufacturing', 'Consumer Applications',
       'Skill Assessment', 'Electronic Design Automation (EDA)',
       'Oil and Gas', 'Enterprise Applications', 'Linux',
       'Virtual Workforce', 'Presentation Software',
       'Bookkeeping and Payroll', 'Diabetes',
       'Human Computer Interaction', 'CivicTech', 'Consumer Research',
       'Ad Server', 'Procurement', 'Quality Assurance', 'Neuroscience',
       'Wedding', 'Penetration Testing', 'Facial Recognition', 'Flowers',
       'Secondhand Goods', 'DSP', 'Robotic Process Automation (RPA)',
       'Health Insurance', 'Twitter', 'Management Consulting',
       'Direct Sales', 'Coffee', 'Tea', 'Ad Retargeting',
       'Commercial Insurance', 'Fast-Moving Consumer Goods', 'Craft Beer',
       'Information and Communications Technology (ICT)',
       'Laundry and Dry-cleaning', 'Cause Marketing', 'Auto Insurance',
       'Charter Schools', 'QR Codes', 'Building Material',
       'Home Improvement', 'Cycling', 'Grocery', 'Boating',
       'Usability Testing', 'Water', 'Audio Recording and Production',
       'Optical Communication', 'B2C', 'Cryptocurrency',
       'Air Transportation', 'Autonomous Vehicles', 'Soccer',
       'Public Transportation', 'GPU', 'Embedded Systems',
       'Product Research', 'Retirement', 'Parking', 'Medical Device',
       'Natural Resources', 'Cannabis', 'Remote Sensing', 'Comics',
       'Handmade', 'Motion Capture', 'Clinical Trials', 'Leasing',
       'Productivity Tools', 'Sporting Goods', 'Property Insurance',
       'Translation Service', 'Environmental Consulting', 'LGBT',
       'Prepaid Cards', 'Industrial Automation', 'Sensor', 'Biofuel',
       'CAD', 'Call Center', 'Recreational Vehicles',
       'In-Flight Entertainment', 'Sports Leagues and Teams',
       'Primary and Urgent Care', 'College Recruiting', 'Golf',
       'Coworking', 'Military', 'Nightlife', 'Technical Support',
       'Marine Technology', 'Tennis', 'Impact Investing', 'Biopharma',
       'Home and Garden', 'Organic', 'RFID', 'Machinery Manufacturing',
       'Simulation', 'Organic Food', 'Adult', 'Ride Sharing',
       'Taxi Service', 'Quantified Self', 'First Aid', 'Emerging Markets',
       'Commercial Lending', 'Archiving Service', 'Textbook', 'Oncology',
       'Data Center Automation', 'Wired Telecommunications',
       'Pollution Control', 'American Football', 'Bakery', 'Nightclubs',
       'Enterprise Resource Planning (ERP)', 'Fertility',
       'Water Purification', 'Smart Building', 'Windows Phone', 'SNS',
       'Outdoor Advertising', 'Personal Care and Hygiene',
       'Gift Registry', 'Fossil Fuels', 'Geothermal Energy',
       'Collection Agency', 'Dental', 'Xbox', 'Assistive Technology',
       'Sponsorship', 'Quantum Computing', 'Vending and Concessions',
       'Adventure Travel', 'Racing',
       'Field-Programmable Gate Array (FPGA)', 'Precision Medicine',
       'Warehouse Automation', 'Continuing Education',
       'Primary Education', 'Secondary Education', 'STEM Education',
       'Vocational Education', 'Smart Contracts', 'Home Appliances',
       'Office Supplies', 'Performing Arts', 'Virtual Desktop',
       'Assisted Living', 'Fuel', 'Therapeutics', 'Green Consumer Goods',
       'Playstation', 'Mining', 'Gift Exchange', 'Mineral', 'eSports',
       'Nursing and Residential Care', 'Windows', 'NFC',
       'Facility Management', 'Tour Operator',
       'Application Specific Integrated Circuit (ASIC)', 'Mental Health',
       'Music Label', 'Audio/Visual Equipment', 'Green Building',
       'Chatbot', "Men's", 'Group Buying', 'Telehealth',
       'Emergency Medicine', 'Aquaculture', 'Mining Technology', 'Laser',
       'Animal Feed', 'Embedded Software', 'Flash Sale', 'Horticulture',
       'Museums and Historical Sites', 'Marine Transportation',
       'Car Sharing', 'Sharing Economy', 'Biomass Energy', 'Fuel Cell',
       'Carbon Capture', 'Nutraceutical', 'Building Maintenance',
       'Indoor Positioning', 'Chemical Engineering', 'Janitorial Service',
       'Industrial Engineering', 'Alternative Medicine',
       'Debt Collections', 'Civil Engineering', 'Personal Development',
       'Nuclear', 'Bioinformatics', 'Intrusion Detection',
       'Hydroelectric', 'Eyewear', 'Catering', 'Fruit',
       'Special Education', 'Office Administration',
       'Document Preparation', 'Made to Order', 'Self-Storage',
       'Hydroponics', 'Wood Processing', 'Cosmetic Surgery',
       'Space Travel', 'Railroad', 'Rehabilitation', 'Industrial Design',
       'Textiles', 'Timeshare', 'Serious Games', 'Underserved Children',
       'Tax Preparation', 'Sex Industry', 'Basketball', 'Precious Metals',
       'Charging Infrastructure', 'Landscaping', 'Franchise',
       'Plant-Based Foods', 'Surfing', 'Smart Cities',
       'Facilities Support Services', 'Non-Fungible Token (NFT)',
       'Social Assistance', 'Card and Board Games', 'Field Support',
       'Multi-level Marketing', 'Hockey', 'Mechanical Design',
       'Last Mile Transportation', 'Diving', 'Outpatient Care', 'Dairy',
       'Music Education', 'Desktop Apps', 'Edutainment', 'Tobacco',
       'Nintendo', 'Shopping Mall', 'Motorsports', 'Tax Consulting',
       'Farmers Market', 'Wildlife Conservation', 'Shipping Broker',
       'Food Trucks', 'Hunting', 'Confectionery', 'Veterinary',
       'Same Day Delivery', 'Local Shopping', 'Paper Manufacturing',
       'Swimming', 'Homeless Shelter', 'Winery', 'Ethereum', 'Parks',
       'Livestock', 'Lingerie', 'MOOC', 'Meat and Poultry',
       'Herbs and Spices', 'Trade Shows', 'Distillery',
       'Limousine Service', 'Google Glass', 'Seafood', 'Drone Management',
       'Table Tennis', 'Courier Service', 'Alternative Protein',
       'Millennials', 'Sex Tech', 'Prediction Markets', 'Baseball',
       'Forestry', 'macOS', 'Advocacy', 'Foundries', 'Sailing', 'Skiing',
       'Generation Z', 'Timber', 'Extermination Service',
       'Decentralized Finance (DeFi)', 'Corrections Facilities',
       'Ports and Harbors', 'Rugby', 'Cricket', 'Volley Ball',
       'Ferry Service', 'RISC', 'Darknet', 'Ultimate Frisbee',
       'Generation Y', 'Roku'], dtype=object)

In [31]:
platform_categories = [
    # Core marketplaces and sharing
    'Marketplace', 'E-Commerce', 'E-Commerce Platforms', 'Online Auctions',
    'Auctions', 'Shopping', 'Crowdfunding', 'Funding Platform',
    'Peer to Peer', 'Sharing Economy', 'Collaborative Consumption',
    'Classifieds', 'Rental', 'Group Buying', 'Vacation Rental', 'Ride Sharing',
    'Car Sharing', 'Food Delivery', 'Delivery Service', 'Ticketing',
    'Online Portals', 'Price Comparison', 'Trading Platform', 'Financial Exchanges',

    # Social & communication platforms
    'Social Media', 'Social Network', 'Communities', 'Social', 'Messaging',
    'VoIP', 'Social Bookmarking', 'Private Social Networking',
    'Professional Networking', 'Social Recruiting', 'Online Forums',
    'Social Shopping', 'Social News', 'Social Entrepreneurship',
    'Dating', 'Content Creators',

    # Content / creator platforms
    'Video Streaming', 'Music Streaming', 'Podcast', 'Video on Demand',
    'Video Sharing', 'Photo Sharing', 'Blogging Platforms', 'Streaming',
    'Content Discovery', 'Content Marketing', 'Content Syndication',

    # Financial / fintech platforms
    'FinTech', 'Payments', 'Mobile Payments', 'Lending', 'Micro Lending',
    'Consumer Lending', 'Trading Platform', 'Virtual Currency', 'Cryptocurrency',
    'Decentralized Finance (DeFi)', 'Financial Exchanges',

    # Developer & SaaS ecosystems
    'Developer Platform', 'Developer APIs', 'API', 'App Discovery', 
    'App Store', 'PaaS', 'Cloud Platform', 'SaaS', 'IaaS',

    # Other multi-sided / intermediation cases
    'Crowdsourcing', 'Job Marketplace', 'Recruiting Platform',
    'Online Education Platform', 'MOOC', 'Coworking', 'Freelance',
    'Funding Platform', 'Affiliate Marketing', 'Influencer Marketing'
]

In [32]:
non_platform_categories = [
    # --- Industrial / Manufacturing / Engineering ---
    "Manufacturing", "Industrial", "Industrial Engineering", "Industrial Design",
    "Industrial Automation", "Machinery Manufacturing", "Mechanical Design",
    "Mechanical Engineering", "Electrical Distribution", "Aerospace", "Automotive",
    "Construction", "Building Material", "Facility Management", "Hardware",
    "Computer Hardware", "Electronics", "Semiconductor", "3D Printing", "Robotics",
    "Embedded Systems", "Embedded Software", "Sensor", "Laser", "Optical Communication",
    "Chemical", "Advanced Materials", "Metals", "Mining", "Oil and Gas", "Energy",
    "Renewable Energy", "Solar", "Wind Energy", "Nuclear", "Power Grid", "Utilities",
    "Smart Building", "Green Building", "Heating  Ventilation  and Air Conditioning (HVAC)",

    # --- Healthcare / Biotech / Pharma / Life Science ---
    "Health Care", "Healthcare Services", "Medical", "Medical Device", "Medical Equipment",
    "Pharmaceutical", "Biotechnology", "Biotech", "Life Science", "Health Diagnostics",
    "Clinical Trials", "Genetics", "Therapeutics", "Precision Medicine", "Hospital",
    "Nursing and Residential Care", "Primary and Urgent Care", "mHealth", "Telehealth",
    "MedTech", "Rehabilitation", "Fertility", "Dental", "Wellness", "Personal Health",
    "Health Insurance", "HealthTech",

    # --- Finance (Traditional / Non-platform) ---
    "Banking", "Insurance", "Wealth Management", "Asset Management", "Private Equity",
    "Venture Capital", "Investment Banking", "Hedge Funds", "Mutual Funds", "Pension",
    "Finance", "Accounting", "Bookkeeping and Payroll", "Credit Bureau", "Credit Cards",
    "Commercial Lending", "Consumer Lending", "Financial Consulting", "Financial Planning",
    "Tax Consulting", "Tax Preparation", "Compliance", "Risk Management", "Audit",

    # --- Professional Services / Consulting / Agencies ---
    "Consulting", "Management Consulting", "IT Consulting", "Business Consulting",
    "Strategy Consulting", "Professional Services", "Legal", "Law", "Legal Tech",
    "Accounting", "Auditing", "Recruiting", "Staffing Agency", "HR Consulting",
    "Corporate Training", "Career Planning", "Coaching", "Outsourcing", "Advisory",
    "Agency", "Creative Agency", "Design Agency", "Marketing Agency", "Advertising Agency",
    "Public Relations", "Digital Marketing", "SEO", "SEM", "Direct Marketing",
    "Brand Marketing",

    # --- Education / Research / Non-Profit ---
    "Education", "EdTech", "E-Learning", "Universities", "Primary Education",
    "Secondary Education", "Vocational Education", "Continuing Education", "Higher Education",
    "Research", "Laboratory", "Institute", "Non Profit", "Charity", "Humanitarian",
    "CivicTech", "Government", "GovTech", "Politics", "Advocacy", "Think Tank",
    "Public Safety", "Homeland Security",

    # --- Real Estate / Construction / Property Services ---
    "Real Estate", "Property Management", "Real Estate Investment", "Property Development",
    "Real Estate Brokerage", "Facilities Support Services", "Facility Management",
    "Architecture", "Interior Design", "Home Renovation", "Home Improvement",
    "Construction Tech", "Civil Engineering", "Smart Building",

    # --- Energy / Agriculture / Environment ---
    "Agriculture", "Farming", "AgTech", "Forestry", "Fisheries", "Aquaculture", "Water",
    "Water Purification", "Waste Management", "Recycling", "GreenTech", "Biofuel",
    "Geothermal Energy", "Fuel Cell", "Pollution Control", "Environmental Consulting",
    "Environmental Engineering", "Sustainability Consulting",

    # --- Retail / Consumer Goods / Food ---
    "Retail", "Wholesale", "Consumer Goods", "Consumer Electronics", "Fashion",
    "Apparel", "Beauty", "Cosmetics", "Food and Beverage", "Restaurants", "Bars",
    "Hospitality", "Hotel", "Travel Agency", "Tour Operator", "Grocery", "Snack Food",
    "Wine And Spirits", "Coffee", "Tea", "Bakery", "Catering", "Packaged Food",
    "Fast-Moving Consumer Goods", "Home Appliances",

    # --- Transportation / Logistics / Supply Chain ---
    "Shipping", "Logistics", "Freight Service", "Warehousing", "Delivery Service",
    "Supply Chain Management", "Fleet Management", "Automotive Manufacturing",
    "Aviation", "Railroad", "Marine Transportation", "Ports and Harbors",
    "Courier Service", "Trucking", "Navigation", "GPS",

    # --- Media / Entertainment (Traditional / Linear) ---
    "Broadcasting", "Media and Entertainment", "Film Production", "TV Production",
    "Radio", "Music Label", "Publishing", "News", "Journalism", "Book Publishing",
    "Magazine", "Advertising", "Creative Content", "Animation", "Video Games",
    "Gaming", "Theatre", "Cinema", "Streaming"
]

In [ ]:
org_clean_df['num_category_platform'] = org_clean_df['category_list'].apply(
    lambda x: sum(1 for cat in platform_categories if cat in x.split(',')) if pd.notna(x) else 0)

In [34]:
org_clean_df['num_category_nonplatform'] = org_clean_df['category_list'].apply(
    lambda x: sum(1 for cat in non_platform_categories if cat in x.split(',')) if pd.notna(x) else 0)

In [35]:
platform_keywords = [
    "platform","marketplace","exchange","network","ecosystem","p2p","peer-to-peer",
    "social","sharing","crowd","community","app store","booking","rental",
    "developers","api","market network","hub","aggregator","on-demand","delivery","wallet"
]

non_platform_keywords = [
    "manufacturing","consulting","venture capital","investment","biotech",
    "medical","healthcare","engineering","construction","banking","insurance",
    "research","education","training","fund","law","legal","energy","factory"
]

In [36]:
org_clean_df['num_keyword_platform'] = org_clean_df['description'].apply(
    lambda x: sum(1 for kw in platform_keywords if kw in x.lower()) if pd.notna(x) else 0
)
org_clean_df['num_keyword_nonplatform'] = org_clean_df['description'].apply(
    lambda x: sum(1 for kw in non_platform_keywords if kw in x.lower()) if pd.notna(x) else 0)

In [39]:
org_clean_df.head(20)

,uuid,description,name,category_list,category_groups_list,short_description,num_category_platform,num_category_nonplatform,num_keyword_platform,num_keyword_nonplatform
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint is a technology platform company that...,Wetpaint,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",Wetpaint offers an online social publishing pl...,1,1,2,1
1,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg Inc. operates a website that enables its ...,Digg,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",Digg operates a website that enables its users...,2,0,0,0
2,df662812-7f97-0b43-9d3e-12f64f504fbb,Meta is a social technology company that enabl...,Meta,"Artificial Intelligence (AI),Augmented Reality...","Artificial Intelligence (AI),Data and Analytic...",Meta is a social technology company that enabl...,2,0,4,1
3,60485007-8856-bbac-aa1b-c535c41f5f47,"Currently in public beta, Omnidrive makes it e...",Omnidrive,"E-Commerce,File Sharing,Internet,Social Media,...","Commerce and Shopping,Internet Services,Media ...",Omnidrive provides online storage facilities t...,2,0,0,0
4,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni is an online community of casual and expe...,Geni,"Collaboration,Communities","Community and Lifestyle,Other",Geni is an online community of genealogists co...,1,0,1,1
5,180ebf67-68d0-2316-e93d-8e1e546330ba,Flektor is a rich-media mash-up platform that ...,Flektor,"Mobile,News,Photography,Software,Video","Content and Publishing,Media and Entertainment...",Flektor is a mash-up platform that enables con...,0,1,1,0
6,d70777cc-14bd-2416-0692-5a483781b78b,Fox Interactive Media is a network of companie...,Fox Interactive Media,"Advertising,Digital Media,Information Services...","Advertising,Content and Publishing,Information...",Fox Interactive Media is a network of companie...,0,2,1,1
7,5da6106f-0d27-0d37-e9d7-dcfeccc1f709,"X, formerly Twitter, is a global social networ...",X (formerly Twitter),"Blogging Platforms,Social Media,Social Network...","Blockchain and Cryptocurrency,Content and Publ...",X is a social networking platform that allows ...,3,0,3,0
8,3d16cb4c-911e-75c0-de5a-15c316b39f98,StumbleUpon is the easiest way to discover new...,StumbleUpon,"Content,Internet,Personalization","Commerce and Shopping,Internet Services,Media ...",StumbleUpon is a discovery engine that finds a...,0,0,1,0
9,56b5f0c1-855f-2ebb-083f-16641f1db2e1,Gizmoz has developed proprietary patented 3D a...,Gizmoz,"3D Technology,Developer Tools","Hardware,Software",Gizmoz develops proprietary patented 3D and an...,0,0,2,0
10,21e77067-5537-408e-cad7-e5e72bb6ad86,Scribd is the unlimited reading subscription t...,Scribd,"Audiobooks,Books,EBooks,File Sharing,News,Podc...","Content and Publishing,Media and Entertainment...",Scribd is an unlimited reading subscription th...,1,2,0,0
11,ea091a8c-40e0-0607-e05a-86e734f94ade,Slacker Radio is next-generation personalized ...,Slacker,"Internet,Mobile,Music","Internet Services,Media and Entertainment,Mobi...","Slacker, an interactive internet radio service...",0,0,0,0
12,59fada33-1595-de45-b362-062a04cf51cf,Lala is a hub for online music discovery and p...,Lala,"Internet,Music,Music Streaming","Internet Services,Media and Entertainment,Musi...","Lala, an online music discovery platform, allo...",1,0,1,0
13,56e82b22-7466-b00b-9035-57ad7b584f65,Helio is a premium mobile service that targets...,Helio Pur Technologies,"Internet,Mobile,Telecommunications","Hardware,Internet Services,Mobile","Helio, a mobile service that targets multimedi...",0,0,2,1
14,e56b0ceb-bb30-bbec-805e-d5dc7412dcb1,eBay is a global online marketplace connecting...,eBay,"Auctions,E-Commerce,Internet,Marketplace,Retail","Commerce and Shopping,Internet Services",eBay is a global online marketplace enabling u...,3,1,2,0
15,7ac8de1f-61b5-b1e8-d67d-6983e765b0cf,Wis.dm is a social network based around simple...,Wis.dm,"Advertising,Big Data,Online Portals,Social Med...","Advertising,Data and Analytics,Internet Servic...",Wis.dm is a social network based around simple...,3,1,2,0
16,b528bd22-cce5-c60c-c79a-b4d995f66993,"MeetMoi, the leading location-based mobile dat...",MeetMoi,"Location Based Services,Mobile,Real Time,Socia...","Data and Analytics,Internet Services,Media and...",MeetMoi is a location-based dating site enabli...,1,0,1,0
17,8cb7f859-e757-0937-a18b-e7992c167203,Postini focuses on two main issues: security a...,Postini,"Cyber Security,Internet,Security,Software","Information Technology,Internet Services,Priva...",Postini offers solutions that protect companie...,0,0,0,0
18,90e234e5-c045-f851-e6aa-291af5d270fe,"As their third major undertaking, [Skype](http...",Joost,"Internet,TV,Video","Internet Services,Media and Entertainment,Video",Joost is an internet TV service that uses peer...,0,0,5,1
19,f09c1228-2e7d-1889-6647-ba5021b2e4ea,CBS is a commercial broadcast television and r...,CBS Entertainment,NaN,NaN,CBS is a commercial broadcast television and r...,0,0,1,0

In [66]:

# Split ord_save_df into 4 parts and save each as a CSV
num_splits = 10
split_dfs = np.array_split(ord_save_df, num_splits)

# Save each split to a separate CSV file
for i, split_df in enumerate(split_dfs):
    split_df.to_csv(f'ord_save_df_part_{i+1}.csv', index=False)

print("Saved ord_save_df into 4 parts: ord_save_df_part_1.csv, ord_save_df_part_2.csv, ord_save_df_part_3.csv, ord_save_df_part_4.csv")
# ...existing code...

/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

Saved ord_save_df into 4 parts: ord_save_df_part_1.csv, ord_save_df_part_2.csv, ord_save_df_part_3.csv, ord_save_df_part_4.csv

In [40]:
platform_df = org_df[org_df['num_match_platform']>0]

In [42]:
platform_df

,uuid,name,type,permalink,cb_url,rank,created_at,updated_at,legal_name,roles,domain,homepage_url,country_code,state_code,region,city,address,postal_code,status,short_description,category_list,category_groups_list,num_funding_rounds,total_funding_usd,total_funding,total_funding_currency_code,founded_on,last_funding_on,closed_on,employee_count,email,phone,facebook_url,linkedin_url,twitter_url,logo_url,alias1,alias2,alias3,primary_role,num_exits,num_match_platform
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,organization,wetpaint,https://www.crunchbase.com/organization/wetpaint,258083.0,2007-05-25 13:51:27,2024-07-09 01:22:43,"wetpaint.com, inc.",company,wetpaint.com,http://www.wetpaint.com/,USA,NY,New York,New York,902 Broadway 11th Floor New,10010,acquired,Wetpaint offers an online social publishing pl...,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",3.0,3.975000e+07,3.975000e+07,USD,2005-06-01,2008-05-19,NaN,51-100,info@wetpaint.com,206-859-6300,https://www.facebook.com/Wetpaint,https://www.linkedin.com/company/recruitment-c...,https://twitter.com/wetpainttv,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,1
2,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,organization,digg,https://www.crunchbase.com/organization/digg,23412.0,2007-05-26 03:03:23,2025-06-17 04:56:34,"Digg Holdings, LLC",company,digg.com,http://www.digg.com,USA,NY,New York,New York,NaN,NaN,acquired,Digg operates a website that enables its users...,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",7.0,4.900000e+07,4.900000e+07,USD,2004-10-11,2024-11-18,NaN,11-50,feedback@digg.com,NaN,http://www.facebook.com/digg,http://www.linkedin.com/company/digg,https://x.com/digg,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,2
4,df662812-7f97-0b43-9d3e-12f64f504fbb,Meta,organization,facebook,https://www.crunchbase.com/organization/facebook,1276.0,2007-05-26 04:22:15,2024-10-01 00:57:57,"Meta Platforms, Inc.","company,investor",meta.com,https://www.meta.com,USA,CA,California,Menlo Park,1 Hacker Way,94025,operating,Meta is a social technology company that enabl...,"Artificial Intelligence (AI),Augmented Reality...","Artificial Intelligence (AI),Data and Analytic...",18.0,5.460882e+10,5.460882e+10,USD,2004-02-04,2025-08-08,NaN,10000+,press@meta.com,NaN,https://www.facebook.com/Meta,https://www.linkedin.com/company/meta,https://x.com/Meta,https://images.crunchbase.com/image/upload/t_c...,Facebook,FB,Meta Platforms,company,1.0,2
8,60485007-8856-bbac-aa1b-c535c41f5f47,Omnidrive,organization,omnidrive,https://www.crunchbase.com/organization/omnidrive,628730.0,2007-05-27 10:25:32,2019-10-03 06:30:53,NaN,company,omnidrive.com,http://www.omnidrive.com,USA,CA,California,Palo Alto,Suite 200 654 High Street,94301,closed,Omnidrive provides online storage facilities t...,"E-Commerce,File Sharing,Internet,Social Media,...","Commerce and Shopping,Internet Services,Media ...",1.0,8.000000e+05,8.000000e+05,USD,2005-11-01,2006-12-01,2008-09-15,unknown,info@omnidrive.com,NaN,http://www.facebook.com/Nomadesk,NaN,http://twitter.com/Nomadesk,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,2
9,4111dc8b-c0df-2d24-ed33-30cd137b3098,Geni,organization,geni,https://www.crunchbase.com/organization/geni,270094.0,2007-06-01 02:52:34,2024-07-23 01:56:23,"Geni, Inc.",company,geni.com,http://www.geni.com,USA,CA,California,West Hollywood,9229 W. Sunset Blvd.,90069,acquired,Geni is an online community of genealogists co...,"Collaboration,Communities","Community and Lifestyle,Other",3.0,1.500000e+07,1.500000e+07,USD,2006-06-01,2009-01-19,NaN,11-50,NaN,NaN,https://www.facebook.com/genidotcom/,https://www.linkedin.com/company/geni-com/about/,http://twitter.com/geni,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4087784,3af0cc93-391e-43d7-a2ba-035bc0889894,SeaSoil,organization,seasoil,https://www.crunchbase.com/organization/seasoil,NaN,2025-10-11 10:23:09,2025-10-11 10:33:24,NaN,company,theseasoil.com,https://www.theseasoil.com/,USA,IN,Indiana,Poland,NaN,5-063,operating,SeaSoil is an innovative biotechnology startup...,"CleanTech,Environmental Consulting,Sharing Eco...","Other,Professional Services,Sustainability",1.0,NaN,NaN,NaN,2022-01-01,2024-01-01,NaN,1-10,Contact@theseasoil.com,NaN,NaN,https://www.linkedin.com/company/seasoil/,NaN,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,1
4087788,c886d849-775f-4cbf-ad8f-7a51f8485044,SagaStar,organization,sagastar,https://www.crunchbase.com/organization/sagastar,NaN,2025-10-11 10:30:43,2025-10-11 10:30:43,"Saga Star, Inc.",company,sagastar.com,https://sagastar.com,USA,WA,Washington,Seattle,NaN,NaN,operating,SagaStar operates a B2C import-export shop off...,"E-Commerce,Industrial,Retail Technology","Commerce and Shopping,Hardware,Manufacturing,S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,1
4087801,7dbc4ac1-163b-40a0-a249-dd2d518403fc,Invest Clearly,organization,invest-clearly,https://www.crunchbase.com/organization/invest...,NaN,2025-10-11 11:02:05,2025-10-11 11:03:15,"Invest Clearly , Inc",company,investclearly.com,https://investclearly.com/,USA,ME,Maine,Gorham,28 State St Suite 4,04038,operating,Invest Clearly an online real estate marketpla...,"Financial Services,FinTech,Real Estate","Financial Services,Real Estate",NaN,NaN,NaN,NaN,2023-01-01,NaN,NaN,1-10,support@investclearly.com,+1 860-304-3228,https://www.facebook.com/Investclearly/,https://www.linkedin.com/company/invest-clearly/,https://x.com/InvestClearly,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,1
4087815,ced41704-9cae-4413-8158-efc23e798da4,XSoft Group,organization,xsoft-group,https://www.crunchbase.com/organization/xsoft-...,NaN,2025-10-11 11:32:22,2025-10-11 11:32:22,XSoft Group Inc.,company,xsoftgroup.com,https://xsoftgroup.com,USA,DE,Delaware,Dover,NaN,NaN,operating,XSoft Group develops custom software solutions...,"Mobile Apps,SaaS,Security,Software","Apps,Mobile,Privacy and Security,Software",NaN,NaN,NaN,NaN,2017-01-01,NaN,NaN,11-50,hey@xsoftgroup.com,374 41 709 100,https://www.facebook.com/xsoftllc,https://www.linkedin.com/company/x-soft,NaN,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,company,NaN,1
4087833,0598e73d-81e8-4b3f-8a19-26d1c69704e6,Just Cobuild,organization,just-cobuild,https://www.crunchbase.com/organization/just-c...,NaN,2025-10-11 12:16:34,2025-10-11 12:16:34,"Just Cobuild, Co",company,NaN,NaN,USA,CA,California,San Francisco,2261 MARKET STREET STE 85230,94114,operating,Just Cobuild is a company that offers technolo...,"Information Technology,SaaS,Software","Information Technology,Software",1.0,5.000000e+04,5.000000e+04,USD,2025-01-01,2025-10-09,NaN,unknown,NaN,+1 4708237152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,company,NaN,1

In [25]:
platform_df[platform_df['name']=='Mission Ventures']

,uuid,name,type,permalink,cb_url,rank,created_at,updated_at,legal_name,roles,domain,homepage_url,country_code,state_code,region,city,address,postal_code,status,short_description,category_list,category_groups_list,num_funding_rounds,total_funding_usd,total_funding,total_funding_currency_code,founded_on,last_funding_on,closed_on,employee_count,email,phone,facebook_url,linkedin_url,twitter_url,logo_url,alias1,alias2,alias3,primary_role,num_exits,num_match_platform
18,c6fff75f-74e6-5e98-494a-037c4202baf8,Mission Ventures,organization,mission-ventures,https://www.crunchbase.com/organization/missio...,267258.0,2007-06-05 12:24:58,2025-04-30 17:56:27,"Mission Ventures, L.P",investor,missionventures.com,http://www.missionventures.com/index.php,USA,CA,California,San Diego,3570 Carmel Mountain Road Suite 200,92130,operating,Mission Ventures is a California-based venture...,"Emerging Markets,Finance,FinTech,Software,Vent...","Financial Services,Lending and Investments,Oth...",NaN,NaN,NaN,NaN,1996-01-01,NaN,NaN,11-50,info@missionventures.com,(858)350-2100,NaN,https://www.linkedin.com/company/mission-ventu...,NaN,https://images.crunchbase.com/image/upload/t_c...,NaN,NaN,NaN,investor,30.0,1